# Generated by Django 3.2.5 on 2021-09-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('unit', models.IntegerField(default=0)),
                ('question1', models.CharField(max_length=1000)),
                ('answer1', models.CharField(max_length=1000)),
                ('question2', models.CharField(max_length=1000)),
                ('answer2', models.CharField(max_length=1000)),
                ('question3', models.CharField(max_length=1000)),
                ('answer3', models.CharField(max_length=1000)),
            ],
        ),
    ]
